### ISSUE TITLE
Падает на это строке "перепортили, перемерзили, пересквернили, перепакостили!"

### ISSUE THREAD

**Issue by PopkovS** [Den4ikAI/ruaccent#2]
text ='перепортили, перемерзили, пересквернили, перепакостили!'
    res = accentizer.process_all(text)
    
    Ошибка:
    Traceback (most recent call last):
  File "D:\projects\creepy_parse\put_ru_accent_and_yo.py", line 22, in <module>
    res = accentizer.process_all(text)
  File "D:\projects\creepy_parse\venv\lib\site-packages\ruaccent\ruaccent.py", line 99, in process_all
    processed_text = self.process_accent(processed_text)
  File "D:\projects\creepy_parse\venv\lib\site-packages\ruaccent\ruaccent.py", line 91, in process_accent
    splitted_text[i] = self.accent_model.put_accent(word)
  File "D:\projects\creepy_parse\venv\lib\site-packages\ruaccent\accent_model.py", line 23, in put_accent
    return self.render_stress(word, predicted_token_class.index('STRESS'))
ValueError: 'STRESS' is not in list

Проблема в слове "перемерзили", сорян это Чехов.
Правится добавлением в venv/Lib/site-packages/ruaccent/dictionary/accents.json

**Comment by Den4ikAI** [comment]
Привет, тут момент такой, что для неизвестных слов (которых нет в словаре) используется нейросеть. Сетка не выдала результата. Добавил проверку вывода нейросетки
